# Interacting with Web APIs

In [12]:
import pandas as pd
import numpy as np
import requests

In [13]:
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'

In [14]:
res = requests.get(url) # You need to connected with Internet.

In [15]:
res

In [16]:
data = res.json()

In [17]:
data[0]['title']

'REF: de-lazify Resampler init'

In [19]:
issues = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])

In [20]:
issues

,number,title,labels,state
0,41245,REF: de-lazify Resampler init,[],open
1,41244,REGR: Avoid error when defining non existing u...,"[{'id': 47229171, 'node_id': 'MDU6TGFiZWw0NzIy...",open
2,41243,REF: simplify SeriesGroupBy._cython_agg_general,[],open
3,41241,BUG:new param [use_nullable_dtypes] of pd.read...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
4,41238,BUG: Frozensets are not supported as indices.,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
5,41237,Confusing error message when SQLAlchemy is not...,"[{'id': 47232590, 'node_id': 'MDU6TGFiZWw0NzIz...",open
6,41236,Optimising Series.nunique for Nan values #40865,"[{'id': 57296398, 'node_id': 'MDU6TGFiZWw1NzI5...",open
7,41234,Regression: concatenating `MultiIndex` with em...,"[{'id': 1218227310, 'node_id': 'MDU6TGFiZWwxMj...",open
8,41233,BUG: histogram plot ignores `xlabel` and `ylab...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
9,41232,ENH: Add num_formats parameter for the xlsxw...,"[{'id': 49254273, 'node_id': 'MDU6TGFiZWw0OTI1...",open
10,41227,BUG: read_excel trailing blank rows and columns,[],open
11,41226,"DOC: Add hint for ""Product space too large""","[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",open
12,41225,ENH: The XLS_SIGNATURE is too restrictive,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
13,41223,BUG: to_string truncation row with index=False,[],open
14,41217,[ArrowStringArray] use pyarrow.compute.match_s...,"[{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...",open
15,41216,BUG: Cannot change the data type in the data f...,"[{'id': 2085877452, 'node_id': 'MDU6TGFiZWwyMD...",open
16,41215,"BUG: Series.replace(List, ...) changes the dty...","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
17,41213,Numpy Import Error,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
18,41212,ENH: 'Efficient' resampling with custom non-un...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
19,41207,DEPS: remove most of distutils usage #41199,"[{'id': 76865106, 'node_id': 'MDU6TGFiZWw3Njg2...",open
20,41206,QST: ERROR in Jupyter using pandas module: Imp...,"[{'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOT...",open
21,41205,DOC: Add Lux to Pandas Ecosystem page,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",open
22,41203,TYP: Fix typing in ExtensionDtype registry,"[{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...",open
23,41201,TYP: io.parsers,"[{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...",open
24,41199,DEPS: remove distutils,"[{'id': 527603109, 'node_id': 'MDU6TGFiZWw1Mjc...",open
25,41196,To numpy float int,[],open
26,41195,TST: refactored tests to use parametrize inste...,"[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...",open
27,41194,ENH: use native filesystem (if available) for ...,"[{'id': 685114413, 'node_id': 'MDU6TGFiZWw2ODU...",open
28,41193,BUG: dataframe setitem error on size incompati...,"[{'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyM...",open
29,41188,BUG: df.hist by column alongside with specifie...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open